# Deployment using CSP. This does require you to download the QCOW from the Avi customer portal.
# Using the relative, or absolute location of the file will allow you to upload, and configure the CSP service.
# TODO: create the controller service on CSP
#       modify the network interfaces
#
- name: Avi Controller | CSP | Requirements
  include: csp/requirements.yml

- name: Avi Controller | CSP | Image deploy
  include: csp/qcow_deploy.yml

- name: Avi Controller | CSP | Metafile deploy
  include: csp/metafile_deploy.yml

- name: Avi Controller | CSP | Service deploy
  include: csp/service_deploy.yml

#- meta: end_play
