---
- name: Check existing Docker container is running
  shell: docker ps -a | grep avinetworks/controller | grep -v CONTAINER
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: con_docker_container_exists

- name: Stop existing Avi Controller Docker container
  shell: docker stop `docker ps -a | grep avinetworks/controller | grep -v CONTAINER | awk '{printf "%s\\n",$1}'`
  when: con_docker_container_exists.rc == 0

- name: Remove existing Avi Controller Docker container
  shell: docker rm -f `docker ps -a | grep avinetworks/controller | grep -v CONTAINER | awk '{printf "%s\\n",$1}'`
  when: con_docker_container_exists.rc == 0

- name: Check for existing Avi Controller Docker image
  shell: docker images | grep avinetworks/controller
  ignore_errors: true
  changed_when: false
  failed_when: false
  register: con_docker_image_exists

- name: Removing existing Avi Controller Docker images
  shell: docker rmi -f `docker images | grep avinetworks/controller | grep -v REPOSITORY | awk '{printf "%s\\n",$3}'`
  ignore_errors: true
  when: con_docker_image_exists.rc == 0

- name: Load the {{ version }} Avi Controller image from Docker Hub
  shell: "docker pull avinetworks/controller:{{ version }}"
