---
# We must do this step first just in case we need to override defaults from the supplied package
- block:
    - name: Avi Controller | Docker | Deploy the image from the package
      copy: src={{ package_source }} dest={{ package_dest }}
    - name: Avi Controller | Docker | Load the image from the package
      shell: "docker load -q -i {{ package_dest }} | awk -F':' '{print $3}'"
      register: load_docker_image
    - set_fact:
        se_version: "{{ load_docker_image.stdout }}"
        se_image: "avinetworks/se:{{ load_docker_image.stdout }}"
  when: package_deploy

- name: Avi Controller | Docker | Check if specified image already exists.
  shell: "docker images -q {{ con_image }}"
  changed_when: false
  register: docker_match

- name: Avi Controller | Docker | Load the image from docker hub
  shell: "docker pull {{ con_image }}"
  register: load_docker_hub
  changed_when: "'Status: Image is up to date' not in load_docker_hub.stdout"
  when:
    - docker_repo == None
    - not package_deploy
    - docker_match.stdout == "" or con_version == "latest"

- name: Avi Controller | Docker | Log into the custom docker repository
  shell: "docker login -u {{ docker_repo_user }} -p {{ docker_repo_password}} {{ docker_repo }}"
  register: docker_repo_login
  when:
    - docker_repo != None
    - not package_deploy
    - docker_match.stdout == "" or con_version == "latest"
    - docker_repo_user != None and docker_repo_password != None

- name: Avi Controller | Docker | Load the image from custom docker repository
  shell: "docker pull {{ docker_repo }}/{{ con_image }}"
  register: load_docker_repo
  changed_when: "'Status: Image is up to date' not in load_docker_repo.stdout"
  when:
    - docker_repo != None
    - not package_deploy
    - docker_match.stdout == "" or con_version == "latest"

- name: Avi Controller | Docker | Get our desired docker image id.
  shell: "docker images -q {{ con_image }}"
  changed_when: false
  register: docker_image

- name: Avi Controller | Docker | Get list of running avicontroller containers
  shell: "docker ps -q -f name=avicontroller "
  changed_when: false
  register: running_con_containers

- name: Avi Controller | Docker | Check if desired version is already running.
  shell: "docker ps -q -f ancestor={{ docker_image.stdout }}"
  changed_when: false
  register: desired_running

- name: Avi Controller | Check for an existing avicontroller service
  stat:
    path: "{{ item }}"
  register: service_installed
  with_items:
    - /etc/systemd/system/avicontroller.service
    - /etc/init.d/avicontroller
    - /etc/init/avicontroller.conf

- name: Avi Controller | Stop avicontroller service
  service: name=avicontroller enabled=no state=stopped
  register: stopped_service
  when:
    - "{{ item.stat.exists }} == true"
    - desired_running.stdout == ""
  with_items: "{{ service_installed.results }}"

- name: Avi Controller | Docker | Stop and Remove the container if it's not the desired version.
  shell: "docker stop {{ item }} && docker rm -f {{ item }}"
  with_items:
    - "{{ running_con_containers.stdout_lines }}"
  when:
    - item not in desired_running.stdout_lines
    - stopped_service.changed
