---
# Deploy the image from a source
- name: Avi Controller | Docker | Deploy the image from the Package
  copy: src={{ package_source }} dest={{ package_dest }}
  when: package_deploy

- name: Avi Controller | Docker | Load the image from the Package
  shell: "docker load -i {{ package_dest }}"
  when: package_deploy

- name: Avi Controller | Docker | Load the image from Docker Hub
  shell: "docker pull {{ con_image }}"
  when: docker_repo == None and not package_deploy

- name: Avi Controller | Docker | Load the image from custom Docker Repository
  shell: "docker pull {{ docker_repo }}/{{ con_image }}"
  when: docker_repo != None and not package_deploy

- name: Avi Controller | Docker | Get list of running controller containers
  shell: "docker ps ancestor=avinetworks/controller -q"
  register: running_con_containers

- name: Avi Controller | Docker | Check if desired version is already running.
  shell: "docker ps -f ancestor={{ con_image }} -q"
  register: desired_running

- name: Avi Controller | Docker | Stop and remove the container if it's not the desired version
  shell: "docker stop {{ item }} && docker rm -f {{ item }}"
  with_items:
    - "{{ running_con_containers.stdout_lines }}"
  when: item not in desired_running.stdout_lines
