---
# tasks file for avinetworks.avicontroller
- name: Avi Controller | Check minimum requirements
  include: requirements.yml
  tags:
    - requirements

- name: Avi Controller | Copy setup.json to controller
  copy: src="{{ setup_json }}" dest="{{ con_disk_path }}/setup.json"
  when: setup_json != None

- name: Avi Controller | Perform Docker tasks
  include: docker.yml

- name: Avi Controller | Install the Avi Controller systemd service
  include: services/systemd.yml
  when: ansible_service_mgr == 'systemd'

- name: Avi Controller | Install the Avi Controller init.d service
  include: services/initd.yml
  when: ansible_service_mgr != 'systemd'
