---
# tasks file for avinetworks.avicontroller
- name: Check minimum requirements
  include: requirements.yml
  tags:
    - requirements

- name: Stop Avi Controller service
  service:
    name: avicontroller
    enabled: no
    state: stopped
  ignore_errors: true

- name: Perform Docker tasks
  include: docker.yml

- name: Install the Avi Controller systemd service
  include: services/systemd.yml
  when: ansible_service_mgr == 'systemd'

- name: Install the Avi Controller init.d service
  include: services/initd.yml
  when: ansible_service_mgr != 'systemd'

- name: Copy setup.json to controller
  copy:
    src: "{{ setup_json }}"
    dest: "{{ con_disk_path }}/setup.json"
  when: setup_json != None

- name: Start Avi Controller service
  service:
    name: avicontroller
    enabled: yes
    state: started
