- name: Avi Controller | Deploy the avicontroller service | init.d
  template: src=avicontroller.j2 dest=/etc/init.d/avicontroller mode=0744
  register: avicontroller_service

- name: Avi Controller | Deploying rc links
  file: src=/etc/init.d/avicontroller dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avicontroller
    - /etc/rc1.d/K99avicontroller
    - /etc/rc2.d/S99avicontroller
    - /etc/rc3.d/S99avicontroller
    - /etc/rc4.d/S99avicontroller
    - /etc/rc5.d/S99avicontroller
    - /etc/rc5.d/K99avicontroller

- name: Avi Controller | Restart the avicontroller service | init.d
  service: name=avicontroller enabled=yes state=restarted
  when: avicontroller_service.changed or load_docker_repo.changed or load_docker_hub.changed
