---
- name: Avi Controller | Services | init.d | Set container env for non-systemd
  set_fact:
    env_variables_extras: "{{ env_variables_extras + ['NON_SYSTEMD=1'] }}"

- name: Avi Controller | Services | init.d | Deploy the avicontroller service
  template: src=avicontroller.j2 dest=/etc/init.d/avicontroller mode=0744
  register: avicontroller_service

- name: Avi Controller | Services | init.d | Deploy the avicontroller_watcher.sh script
  copy: src=init/avicontroller_watcher.sh dest=/etc/init.d/avicontroller_watcher.sh mode=0744
  register: avicontroller_watcher_sh

- name: Avi Controller | Services | init.d | Deploy the avicontroller_watcher service
  copy: src=init/avicontroller_watcher dest=/etc/init.d/avicontroller_watcher mode=0744
  register: avicontroller_watcher_service

- name: Avi Controller | Services | init.d | Removing avicontroller rc links
  file: path={{ item }} state=absent
  with_items:
    - /etc/rc0.d/K99avicontroller
    - /etc/rc1.d/K99avicontroller
    - /etc/rc2.d/S99avicontroller
    - /etc/rc3.d/S99avicontroller
    - /etc/rc4.d/S99avicontroller
    - /etc/rc5.d/S99avicontroller
    - /etc/rc6.d/K99avicontroller

- name: Avi Controller | Services | init.d | Deploying avicontroller_watcher rc links
  file: src=/etc/init.d/avicontroller_watcher dest={{ item }} state=link
  with_items:
    - /etc/rc0.d/K99avicontroller_watcher
    - /etc/rc1.d/K99avicontroller_watcher
    - /etc/rc2.d/S99avicontroller_watcher
    - /etc/rc3.d/S99avicontroller_watcher
    - /etc/rc4.d/S99avicontroller_watcher
    - /etc/rc5.d/S99avicontroller_watcher
    - /etc/rc6.d/K99avicontroller_watcher

- name: Avi Controller | Services | init.d | Restart the avicontroller_watcher service
  service: name=avicontroller_watcher enabled=yes state=restarted
  when: avicontroller_service.changed or
        avicontroller_watcher_service.changed or
        load_docker_repo.changed or
        load_docker_hub.changed

- name: Avi Controller | Services | init.d | Start the avicontroller_watcher service
  service: name=avicontroller_watcher enabled=yes state=started
