---
- name: Avi Controller | Deploy the Avi Controller service | systemd
  template: src=avicontroller.service.j2 dest=/etc/systemd/system/avicontroller.service mode=0744
  notify: Avi Controller | Restart the Avi Controller service | systemd
