---
- name: Avi Controller | Services | systemd | Deploy the avicontroller service
  template: src=systemd/avicontroller.service.j2 dest=/etc/systemd/system/avicontroller.service mode=0744
  register: avicontroller_service

- name: Avi Controller | Services | systemd | Restart the avicontroller service
  systemd: daemon_reload=yes name=avicontroller enabled=yes state=restarted
  when: avicontroller_service.changed or
        load_docker_repo.changed or
        load_docker_hub.changed

- name: Avi Controller | Services | systemd | Start the avicontroller service
  systemd: daemon_reload=yes name=avicontroller enabled=yes state=started
