---
- name: Avi Controller | Services | systemd | 16.x | Deploy the avicontroller service
  template:
    src: 16.x/avicontroller.service.j2
    dest: /usr/lib/systemd/system/avicontroller.service
    mode: 0644
  register: avicontroller_service
  when: con_version|version_compare('17.0.0, '<')

- name: Avi Controller | Services | systemd | 17.x+ | Deploy the avicontroller service
  copy:
    src: systemd/avicontroller.service
    dest: /usr/lib/systemd/system/avicontroller.service
    mode: 0644
  register: avicontroller_service
  when: con_version|version_compare('17.0.0', '>=')

# Standard steps
- name: Avi Controller | Services | systemd | Restart the avicontroller service
  systemd: daemon_reload=yes name=avicontroller enabled=yes state=restarted
  when: avicontroller_service.changed or
        load_docker_repo.changed or
        load_docker_hub.changed

- name: Avi Controller | Services | systemd | Start the avicontroller service
  systemd: daemon_reload=yes name=avicontroller enabled=yes state=started
