---
- name: Avi Controller | Docker | Log into the custom docker repository
  shell: "docker login -u {{ docker_repo_user }} -p {{ docker_repo_password}} {{ docker_repo }}"
  register: docker_repo_login
  when:
    - docker_repo != None
    - not package_deploy
    - docker_match.stdout == "" or con_version == "latest"
    - docker_repo_user != None and docker_repo_password != None

- name: Avi Controller | Docker | Load the image from custom docker repository
  shell: "docker pull {{ docker_repo }}/{{ con_image }}"
  register: load_docker_repo
  changed_when: "'Status: Image is up to date' not in load_docker_repo.stdout"
  when:
    - docker_repo != None
    - not package_deploy
    - docker_match.stdout == "" or con_version == "latest"
