---
# This set of tasks is only used when package_deploy is true
- name: Avi Controller | Docker | Deploy the image from the package
  copy: src={{ package_source }} dest={{ package_dest }}

- name: Avi Controller | Docker | Load the image from the package
  shell: "docker load -q -i {{ package_dest }} | awk -F':' '{print $3}'"
  register: load_docker_image

- set_fact:
    con_version: "{{ load_docker_image.stdout }}"
    con_image: "avinetworks/controller:{{ load_docker_image.stdout }}"
